name: Deploy to Firebase

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
    
    - name: Install Functions Dependencies
      run: |
        cd functions
        npm ci
    
    - name: Deploy to Firebase
      run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project smartseason-39cdb
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
